// Mock Data for HRMS System

export const mockTenants = [
  {
    id: 'tenant-001',
    name: 'Indian Bank - Head Office',
    code: 'INDBNK-HO',
    location: 'Mumbai',
    employees: 5000,
    status: 'active',
  },
  {
    id: 'tenant-002',
    name: 'Indian Bank - Regional Office',
    code: 'INDBNK-RO',
    location: 'Delhi',
    employees: 3000,
    status: 'active',
  },
  {
    id: 'tenant-super',
    name: 'Development - Super Admin',
    code: 'DEV-SUPER',
    location: 'Development',
    employees: 1,
    status: 'active',
  },
];

export const mockRoles = [
  { id: 'role-employee', name: 'Employee', permissions: ['view_payslip', 'apply_leave', 'submit_expense', 'view_profile'] },
  { id: 'role-manager', name: 'Manager', permissions: ['approve_leave', 'approve_expense', 'view_team', 'view_reports'] },
  { id: 'role-hr', name: 'HR Administrator', permissions: ['manage_employees', 'configure_system', 'view_all_reports', 'manage_policies'] },
  { id: 'role-payroll', name: 'Payroll Administrator', permissions: ['process_payroll', 'manage_compliance', 'view_payroll_reports'] },
];

export const mockUsers = [
  {
    id: 'user-001',
    tenantId: 'tenant-001',
    email: 'rajesh.kumar@indianbank.com',
    password: 'password123',
    name: 'Rajesh Kumar',
    role: 'Employee',
    designation: 'Senior Accountant',
    department: 'Finance',
    status: 'active',
    joinDate: '2020-01-15',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
  },
  {
    id: 'user-002',
    tenantId: 'tenant-001',
    email: 'priya.sharma@indianbank.com',
    password: 'password123',
    name: 'Priya Sharma',
    role: 'Manager',
    designation: 'Branch Manager',
    department: 'Operations',
    status: 'active',
    joinDate: '2018-03-20',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
  },
  {
    id: 'user-003',
    tenantId: 'tenant-001',
    email: 'admin.hr@indianbank.com',
    password: 'password123',
    name: 'Deepa Gupta',
    role: 'HR Administrator',
    designation: 'HR Manager',
    department: 'Human Resources',
    status: 'active',
    joinDate: '2019-06-10',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Deepa',
  },
  {
    id: 'user-004',
    tenantId: 'tenant-001',
    email: 'payroll@indianbank.com',
    password: 'password123',
    name: 'Amit Verma',
    role: 'Payroll Administrator',
    designation: 'Payroll Manager',
    department: 'Finance',
    status: 'active',
    joinDate: '2017-11-05',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amit',
  },
  {
    id: 'user-005',
    tenantId: 'tenant-001',
    email: 'suresh.patel@indianbank.com',
    password: 'password123',
    name: 'Suresh Patel',
    role: 'Employee',
    designation: 'Relationship Manager',
    department: 'Retail Banking',
    status: 'active',
    joinDate: '2021-07-01',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh',
  },
  {
    id: 'user-super-admin',
    tenantId: 'tenant-super',
    email: 'superadmin@indianbank.com',
    password: 'admin123',
    name: 'Super Admin',
    role: 'HR Administrator',
    designation: 'Super Administrator',
    department: 'IT',
    status: 'active',
    joinDate: '2020-01-01',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SuperAdmin',
  },
];

export const mockEmployees = [
  {
    id: 'emp-001',
    tenantId: 'tenant-001',
    employeeCode: 'IB-20001',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh.kumar@indianbank.com',
    phone: '9876543210',
    dateOfBirth: '1990-05-15',
    gender: 'Male',
    status: 'Active',
    joinDate: '2020-01-15',
    designation: 'Senior Accountant',
    department: 'Finance',
    reportingManager: 'user-002',
    location: 'Mumbai',
    salary: 750000,
    ctc: 850000,
    pfNumber: 'MH/2020/00001',
    esiNumber: '35000001234567890',
    panNumber: 'ABCDE1234F',
    aadhaarNumber: 'XXXX-XXXX-1234',
    bankAccount: '1234567890123456',
    ifscCode: 'IBIN0000001',
    address: '123, Business Park, Bandra, Mumbai',
    emergencyContact: 'Priya Kumar',
    emergencyPhone: '9123456789',
    bloodGroup: 'O+',
  },
  {
    id: 'emp-002',
    tenantId: 'tenant-001',
    employeeCode: 'IB-20002',
    firstName: 'Suresh',
    lastName: 'Patel',
    email: 'suresh.patel@indianbank.com',
    phone: '9876543211',
    dateOfBirth: '1992-03-22',
    gender: 'Male',
    status: 'Active',
    joinDate: '2021-07-01',
    designation: 'Relationship Manager',
    department: 'Retail Banking',
    reportingManager: 'user-002',
    location: 'Mumbai',
    salary: 600000,
    ctc: 700000,
    pfNumber: 'MH/2021/00002',
    esiNumber: '35000001234567891',
    panNumber: 'BCDEF2345G',
    aadhaarNumber: 'XXXX-XXXX-5678',
    bankAccount: '1234567890123457',
    ifscCode: 'IBIN0000001',
    address: '456, Marina Heights, Colaba, Mumbai',
    emergencyContact: 'Kavya Patel',
    emergencyPhone: '9123456790',
    bloodGroup: 'B+',
  },
];

export const mockPayroll = [
  {
    id: 'payroll-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    month: 'January',
    year: 2026,
    basicSalary: 500000,
    da: 100000,
    hra: 150000,
    allowances: 50000,
    pfDeduction: 20000,
    esiDeduction: 5000,
    incomeTax: 30000,
    netSalary: 745000,
    status: 'Paid',
    generatedDate: '2026-01-25',
    paidDate: '2026-01-31',
  },
  {
    id: 'payroll-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    month: 'January',
    year: 2026,
    basicSalary: 400000,
    da: 80000,
    hra: 120000,
    allowances: 40000,
    pfDeduction: 16000,
    esiDeduction: 4000,
    incomeTax: 20000,
    netSalary: 600000,
    status: 'Paid',
    generatedDate: '2026-01-25',
    paidDate: '2026-01-31',
  },
];

export const mockLeaves = [
  {
    id: 'leave-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    leaveType: 'Sick Leave',
    startDate: '2026-02-01',
    endDate: '2026-02-03',
    days: 3,
    reason: 'Medical consultation',
    status: 'Approved',
    appliedDate: '2026-01-28',
    approverName: 'Priya Sharma',
  },
  {
    id: 'leave-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    leaveType: 'Casual Leave',
    startDate: '2026-02-10',
    endDate: '2026-02-12',
    days: 3,
    reason: 'Personal work',
    status: 'Pending',
    appliedDate: '2026-01-27',
    approverName: 'Priya Sharma',
  },
];

export const mockExpenses = [
  {
    id: 'expense-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    category: 'Travel',
    amount: 5000,
    description: 'Flight to Delhi for client meeting',
    date: '2026-01-20',
    status: 'Approved',
    receiptUrl: '',
    submittedDate: '2026-01-21',
    approverName: 'Priya Sharma',
  },
  {
    id: 'expense-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    category: 'Accommodation',
    amount: 3500,
    description: 'Hotel stay in Bangalore',
    date: '2026-01-18',
    status: 'Pending',
    receiptUrl: '',
    submittedDate: '2026-01-19',
    approverName: 'Priya Sharma',
  },
];

export const mockPerformance = [
  {
    id: 'appraisal-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    period: 'Q4 2025',
    raterName: 'Priya Sharma',
    overallRating: 4.2,
    communicationRating: 4,
    teamworkRating: 4.5,
    leadershipRating: 4,
    technicalSkillsRating: 4.3,
    comments: 'Excellent performance with strong technical capabilities',
    status: 'Completed',
    date: '2026-01-15',
  },
  {
    id: 'appraisal-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    period: 'Q4 2025',
    raterName: 'Priya Sharma',
    overallRating: 3.8,
    communicationRating: 3.8,
    teamworkRating: 3.9,
    leadershipRating: 3.7,
    technicalSkillsRating: 3.8,
    comments: 'Good performance with consistent improvement',
    status: 'Completed',
    date: '2026-01-15',
  },
];

export const mockAttendance = [
  {
    id: 'att-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    date: '2026-01-27',
    checkIn: '09:00',
    checkOut: '18:00',
    status: 'Present',
    workingHours: 9,
  },
  {
    id: 'att-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    date: '2026-01-28',
    checkIn: '09:15',
    checkOut: '17:45',
    status: 'Present',
    workingHours: 8.5,
  },
  {
    id: 'att-003',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    date: '2026-01-27',
    checkIn: '09:30',
    checkOut: '18:30',
    status: 'Present',
    workingHours: 9,
  },
];

export const mockTaxData = [
  {
    id: 'tax-001',
    tenantId: 'tenant-001',
    employeeId: 'emp-001',
    financialYear: '2025-26',
    grossIncome: 8500000,
    standardDeduction: 50000,
    chapter6aDeductions: 150000,
    otherDeductions: 100000,
    taxableIncome: 8200000,
    taxCalculated: 360000,
    educationCess: 7200,
    totalTax: 367200,
    status: 'Filed',
  },
  {
    id: 'tax-002',
    tenantId: 'tenant-001',
    employeeId: 'emp-002',
    financialYear: '2025-26',
    grossIncome: 7000000,
    standardDeduction: 50000,
    chapter6aDeductions: 150000,
    otherDeductions: 100000,
    taxableIncome: 6700000,
    taxCalculated: 280000,
    educationCess: 5600,
    totalTax: 285600,
    status: 'Filed',
  },
];

export const mockRecruitement = [
  {
    id: 'job-001',
    tenantId: 'tenant-001',
    title: 'Senior Software Engineer',
    department: 'IT',
    status: 'Open',
    postedDate: '2026-01-15',
    applications: 45,
    openPositions: 2,
  },
  {
    id: 'job-002',
    tenantId: 'tenant-001',
    title: 'Relationship Manager',
    department: 'Retail Banking',
    status: 'Open',
    postedDate: '2026-01-10',
    applications: 28,
    openPositions: 3,
  },
];

export const mockDashboardStats = {
  totalEmployees: 5000,
  activeEmployees: 4950,
  onLeaveToday: 120,
  presentToday: 4830,
  absentToday: 50,
  pendingApprovals: 35,
  newJoinings: 12,
  pendingOnboarding: 8,
};

export const mockChartData = [
  { month: 'Jan', applications: 65, hires: 8 },
  { month: 'Feb', applications: 59, hires: 6 },
  { month: 'Mar', applications: 80, hires: 10 },
  { month: 'Apr', applications: 81, hires: 9 },
  { month: 'May', applications: 56, hires: 7 },
  { month: 'Jun', applications: 55, hires: 5 },
];

export const mockNotifications = [
  {
    id: 'notif-001',
    type: 'leave_approval',
    title: 'Leave Request Approved',
    message: 'Your leave request for 2-3 Feb has been approved',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-002',
    type: 'payslip',
    title: 'Payslip Available',
    message: 'Your January 2026 payslip is now available',
    timestamp: '1 day ago',
    read: true,
  },
  {
    id: 'notif-003',
    type: 'appraisal',
    title: 'Performance Appraisal Due',
    message: 'Your Q4 2025 performance appraisal is pending',
    timestamp: '3 days ago',
    read: true,
  },
];
